- name: Create user on server
  hosts: all
  become: yes
  remote_user: "{{ ansible_user }}"
  gather_facts: yes

  tasks:

    - name: Enable Root Login
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin yes'
        state: present
        backup: yes
        insertafter: EOF
      become: yes
      notify:
        - Restart ssh

    - name: Enable password authentication
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication yes'
        state: present
        backup: yes
        insertafter: EOF
      become: yes
      notify:
        - Restart ssh

  handlers:
    - name: Restart ssh
      service:
        name: sshd
        state: restarted
